pageInfo:
  title: Karl's server
  description: Stuff for friends
appConfig:
  disableConfiguration: true
  hideComponents:
    hideSearch: true
    hideSettings: true
    hideFooter: true
    hideHeading: true
  theme: one-dark
  layout: vertical
  iconSize: large
  language: en
  openingMethod: newtab
sections:
  - name: Services
    icon: mdi-server
    items:
      - &ref_0
        title: Watch media
        description: Kinda like netflix but more broken
        icon: si-jellyfin
        url: https://watch.kwkaiser.io
        id: 0_836_watchmedia
    filteredItems:
      - *ref_0
