pageInfo:
  title: Karl's server
  description: Stuff for friends

appConfig:
  theme: default
  layout: auto
  iconSize: medium
  language: en
  openingMethod: newtab

sections:
  - name: Services
    icon: mdi-server
    items:
      - title: Watch media
        description: Kinda like netflix but more broken
        icon: si-jellyfin
        url: https://watch.kwkaiser.io
