apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "grafana-configs"
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        app.kubernetes.io/name: grafana
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: grafana-configs
          configMap:
            name: grafana-configs
            items:
              - key: config.ini
                path: config.ini

      containers:
        - name: grafana
          image: {{ .Values.image_grafana }}
          ports:
            - containerPort: 3000
          args:
            - "--config=/config.ini"

          env:
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana.oauth.client.id
                  key: value

            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana.oauth.client.secret
                  key: value

          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
              subPath: application/grafana

            - name: grafana-configs
              mountPath: config.ini
              subPath: config.ini
              readOnly: false
