apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "prometheus-configs"
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        app.kubernetes.io/name: prometheus
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bulk-nfs

        - name: prometheus-configs
          configMap:
            name: prometheus-configs
            items:
              - key: configuration.yaml
                path: configuration.yaml

      containers:
        - name: prometheus
          image: {{ .Values.image_prometheus }}
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

          volumeMounts:
            - name: data
              mountPath: /prometheus
              subPath: application/prometheus

            - name: prometheus-configs
              mountPath: /etc/prometheus/prometheus.yml
              subPath: configuration.yaml
              readOnly: false
